### ISSUE TITLE
GitHub topic clash

### ISSUE THREAD

**Issue by mxmilkiib** [leadvertex/plugin-core#1]
Hello! I'm afraid there's a bit of a problem, in that the lv2 GitHub topic has been used for the LV2 plugin format, and now it's getting confusing when browsing. Can I possibly request that a slightly different tag be used for your organisation/framework tag?

**Comment by XAKEPEHOK** [comment]
I don't understand about which problem you say. Can you explain more details or give me links/screenshots?

**Comment by mxmilkiib** [comment]
[LV2](https://github.com/lv2/lv2) is an audio/MIDI/etc [plugin format](https://lv2plug.in/). The GitHub topic '[lv2](https://github.com/topics/lv2)' has been used to tag plugins and related projects, but now a number of the [leadvertex](https://github.com/leadvertex) projects are also using the 'lv2' tag which unfortunately makes browsing the tag confusing and less helpful.

**Comment by XAKEPEHOK** [comment]
Very interesting) For us, lv2 means "leadvertex 2". And until that moment i didn't think about global search by tags/topics. 
Ok, i got you point, lv2 topic was removed from ours repo's

**Comment by mxmilkiib** [comment]
Thank you very much!
